"""Starter dataset: 24 hand-written sentences per variety.

This is a toy set so the project runs end to end. For real numbers, replace
load_data() with a loader for a real corpus (ICE, GLoWbE, TwitterAAE, etc.).
"""

DATA = {
    "American": [
        "I'm gonna grab some groceries after work, do you need anything from the store?",
        "The truck got stuck in the parking lot because of all the snow.",
        "Can you mail me the check by Friday? I'll deposit it at the bank.",
        "We took the elevator to the second floor and found the restroom.",
        "My neighbor painted his fence gray last weekend.",
        "She's studying math at a state university in Ohio.",
        "Put the trash in the can and take the cookies out of the oven.",
        "I just got a new cell phone and the battery is awesome.",
        "He wore sneakers and a sweater to the football game.",
        "Did you check the color of the faucet before you bought it?",
        "The movie theater downtown is offering a discount on Tuesdays.",
        "We need to fill up the gas tank before we hit the highway.",
        "Our apartment has a great view of the downtown skyline.",
        "I'll call you when I get off work around five.",
        "The kids are playing soccer in the yard with their cleats on.",
        "She ordered french fries and a soda at the drive-through.",
        "I have a doctor's appointment next week, so I'll take a vacation day.",
        "He graduated from high school and enrolled in a community college.",
        "Do you want me to organize the schedule for the whole semester?",
        "The mailman left a package on the porch this morning.",
        "We rented a car and drove all the way to Texas.",
        "I think the gas prices are crazy right now.",
        "Honestly, I could use a vacation after this quarter.",
        "The line at the pharmacy was so long that I almost left.",
    ],
    "British": [
        "I'm just popping to the shops, shall I get you some biscuits?",
        "The lorry broke down on the motorway so we were late for the meeting.",
        "Could you post me the cheque by Friday? I'll pay it into my account.",
        "We took the lift to the first floor and found the loo.",
        "My neighbour painted his fence grey last weekend.",
        "She's studying maths at university in Manchester.",
        "Pop the rubbish in the bin and take the biscuits out of the oven, would you?",
        "I've just got a new mobile and the battery is brilliant.",
        "He wore trainers and a jumper to the football match.",
        "Did you check the colour of the tap before you bought it?",
        "The cinema in town does a discount on Tuesdays, apparently.",
        "We need to fill up with petrol before we get on the motorway.",
        "Our flat has a lovely view over the park, whilst the rent is dreadful.",
        "I'll ring you when I finish work at about five.",
        "The children are playing football in the garden in their wellies.",
        "She ordered chips and a fizzy drink at the takeaway.",
        "I've got a doctor's appointment next week, so I'll take a day of annual leave.",
        "He finished sixth form and went off to uni.",
        "Shall I organise the timetable for the whole term?",
        "The postman left a parcel on the doorstep this morning.",
        "We hired a car and drove all the way to Cornwall.",
        "I reckon the petrol prices are mental at the moment.",
        "I'm absolutely knackered and could do with a holiday.",
        "The queue at the chemist was so long I nearly gave up.",
    ],
    "Australian": [
        "I'm just heading to the servo, do you want a snag from the sausage sizzle?",
        "The ute broke down on the highway so we were late to the barbie.",
        "Can you send me the cheque by Friday? I'll pop it in the bank, mate.",
        "We took the lift to the first floor and found the dunny.",
        "My neighbour painted his fence grey last weekend, reckon it looks good.",
        "She's studying maths at uni in Melbourne.",
        "Chuck the rubbish in the bin and grab a few tinnies from the esky.",
        "I just got a new mobile and the battery is heaps good.",
        "He wore thongs and a hoodie to the footy.",
        "Did you check the colour of the tap before you bought it, mate?",
        "The pictures in town does a discount on Tuesdays, no worries.",
        "We need to fill up the car before we hit the highway to Perth.",
        "Our place has a ripper view of the beach, but the rent is a killer.",
        "I'll give you a bell when I knock off work around five.",
        "The kids are playing footy in the backyard in their bare feet.",
        "She ordered chips and a lemonade at the servo.",
        "I've got a doctor's appointment next week so I'll chuck a sickie.",
        "He finished Year 12 and went off to uni.",
        "Reckon I should organise the roster for the whole term.",
        "The postie left a parcel on the verandah this morning.",
        "We hired a car and drove all the way to Darwin, no dramas.",
        "Reckon the petrol prices are cooked at the moment, mate.",
        "I'm absolutely stuffed and could do with a holiday, to be fair.",
        "The queue at the bottle-o was heaps long, so I gave up.",
    ],
    "Indian": [
        "I am going to market only, do you want me to bring something?",
        "The lorry got stuck on the highway so we are late for the meeting.",
        "Kindly send me the cheque by Friday, I will deposit it in the bank.",
        "We took the lift to the first floor and found the washroom.",
        "My neighbour has painted his gate grey last weekend itself.",
        "She is doing her engineering from a college in Pune.",
        "Please do the needful and revert back to me at the earliest.",
        "I have bought a new mobile and the battery backup is very good.",
        "He is having two sisters and one brother in Hyderabad.",
        "What is your good name, and where are you staying currently?",
        "The cinema hall in town gives a discount on Tuesdays only.",
        "We have to fill petrol before going on the highway.",
        "Our flat is having a nice view, but the rent is too much.",
        "I will give you a missed call when I am free from the office.",
        "The children are playing cricket in the compound since morning.",
        "She ordered one plate of samosa and a cold drink at the canteen.",
        "I have a doctor's appointment next week, so I will take one day leave.",
        "He passed out of his college last year and is now preparing for the exams.",
        "Can you prepone the meeting to Monday, sir?",
        "The postman has left a parcel at the door in the morning.",
        "We went by train to Jaipur and stayed in a lodge for two nights.",
        "The petrol prices are going up day by day, na?",
        "I am feeling very tired, I need a holiday only.",
        "The queue at the ration shop was too long, so I came back.",
    ],
    "Singaporean": [
        "I go makan first, you want me to tapao anything or not?",
        "The lorry broke down on the expressway so we late for the meeting lah.",
        "Can you send me the cheque by Friday? I go bank deposit already.",
        "We take the lift to the first floor then find the toilet.",
        "My neighbour paint his gate grey last weekend, quite nice leh.",
        "She studying maths in NUS, very stress one.",
        "Throw the rubbish in the bin, then take the cookies out from the oven can?",
        "I just bought a new handphone, the battery very power.",
        "He wear slippers and a jacket to the football match, cannot make it.",
        "You check the colour of the tap before you buy or not?",
        "The cinema at the mall got discount on Tuesday, you know?",
        "We must fill petrol first before we go on the expressway.",
        "Our flat got nice view but the rent very expensive lah.",
        "I call you when I finish work around five, okay?",
        "The kids playing football at the void deck already.",
        "She order chicken rice and a kopi at the hawker centre.",
        "I got doctor appointment next week so I take one day leave.",
        "He finish poly then go army for two years.",
        "Can you help me organise the schedule for the whole term or not?",
        "The postman leave a parcel at the door this morning.",
        "We rent a car and drive all the way to Johor, so tiring.",
        "Petrol price now very high, aiyo.",
        "I so tired, need a holiday sia.",
        "The queue at the pharmacy so long, I give up already.",
    ],
}


def load_data():
    """Returns texts, labels, groups.

    The same 24 situations are written in every variety, so sentence i of each
    variety shares a group id. Splits must keep a group together, otherwise the
    model sees the same topic under other labels during training.
    """
    texts, labels, groups = [], [], []
    for label, sentences in DATA.items():
        for i, s in enumerate(sentences):
            texts.append(s)
            labels.append(label)
            groups.append(i)
    return texts, labels, groups
